
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300037574
 */
public class artintern extends javax.swing.JFrame {

    /**
     * Creates new form artintern
     */
    public artintern() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 121, 182)); //set background colour 
    }
    
    //array of strings
    String alllinks [] = {"https://www.georgiancollege.ca/blog/newsroom/high-school-students-get-hands-on-experience-in-skilled-trades/",
            "https://www.metmuseum.org/about-the-met/internships/high-school","https://www.mfa.org/programs/teen-programs", 
    "https://jobs.jobvite.com/ago/jobs/internships?t=Intern", "https://www.theworks.ab.ca/education"}; //array of strings
    
    //method to use hyperlink
    public static String hyperlink (String link){ 
        try {
            URI uri = new URI(link);
            Desktop desktop = null;
            if (Desktop.isDesktopSupported()) {
              desktop = Desktop.getDesktop();
            }

      if (desktop != null)
            desktop.browse(uri);
        } catch (IOException ioe) {
          ioe.printStackTrace(); 
        } catch (URISyntaxException use) {
          use.printStackTrace();
        } 
        return link; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNWILDLIFE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTNRBC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNUOFT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTNGOOGLE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNQUEENS = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BTNSICKKIDS = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTNAGO = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BTNGEORGIAN = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BTNWORKS = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BTNMET = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BTNFINE = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        BTNWILDLIFE.setText("Wildlife");
        BTNWILDLIFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNWILDLIFEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("STEM Internship Opportunities!");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("4. Wildlife Leadership");

        BTNRBC.setText("RBC");
        BTNRBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRBCActionPerformed(evt);
            }
        });

        jLabel9.setText("Get outside and connect with the environment while learning!");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("1. RBC Summer Tech Labs");

        BTNUOFT.setText("UofT");
        BTNUOFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUOFTActionPerformed(evt);
            }
        });

        jLabel2.setText("Design, develop, and test a prototype for a business unit at RBC!");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("5. UofT Academic Program");

        BTNGOOGLE.setText("Google");
        BTNGOOGLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGOOGLEActionPerformed(evt);
            }
        });

        jLabel11.setText("Challenges, engaging projects, and networking at University of Toronto!");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("2. Google Computer Science");

        BTNQUEENS.setText("Queen's");
        BTNQUEENS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNQUEENSActionPerformed(evt);
            }
        });

        jLabel5.setText("Innovate, program, and design at the Google office!");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("6. Queen's Computing");

        BTNSICKKIDS.setText("Sick Kids");
        BTNSICKKIDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSICKKIDSActionPerformed(evt);
            }
        });

        jLabel13.setText("Work in a computing research lab with computing professors!");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("3. StAr Sick Kids");

        jLabel7.setText("Interact with world-renowned researchers and medical professionals!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNAGO.setText("AGO");
        BTNAGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAGOActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel14.setText("ARTS Internship Opportunities!");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setText("4. Art Gallery of Ontario");

        BTNGEORGIAN.setText("Georgian");
        BTNGEORGIAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGEORGIANActionPerformed(evt);
            }
        });

        jLabel16.setText("Introduce new and exciting ideas to the Gallery!");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("1. Experience Georgian");

        BTNWORKS.setText("Works");
        BTNWORKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNWORKSActionPerformed(evt);
            }
        });

        jLabel18.setText("Learn the foundation of all museum and gallery work.");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setText("5. The Works");

        BTNMET.setText("Met");
        BTNMET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMETActionPerformed(evt);
            }
        });

        jLabel20.setText("Combining in class and hands-on mentorship, join the Works!");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setText("2. The Met");

        jLabel22.setText("Calling all artists, you can get paid while working at a museum!");

        BTNFINE.setText("Fine Arts");
        BTNFINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFINEActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel25.setText("3. Museum of Fine Arts");

        jLabel26.setText("12-month internship. Hands-on projects and artwork!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(125, 125, 125)
                            .addComponent(BTNFINE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNMET)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(123, 123, 123)
                                .addComponent(BTNGEORGIAN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNAGO))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNWORKS)))
                                .addGap(8, 8, 8)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(BTNGEORGIAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(BTNMET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(BTNFINE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(BTNAGO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(BTNWORKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNWILDLIFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNWILDLIFEActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[3]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNWILDLIFEActionPerformed

    private void BTNRBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRBCActionPerformed

        hyperlink(alllinks[0]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNRBCActionPerformed

    private void BTNUOFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUOFTActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[4]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNUOFTActionPerformed

    private void BTNGOOGLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGOOGLEActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[1]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNGOOGLEActionPerformed

    private void BTNQUEENSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNQUEENSActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[5]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNQUEENSActionPerformed

    private void BTNSICKKIDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSICKKIDSActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[2]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNSICKKIDSActionPerformed

    private void BTNAGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAGOActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[3]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNAGOActionPerformed

    private void BTNGEORGIANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGEORGIANActionPerformed

        hyperlink(alllinks[0]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNGEORGIANActionPerformed

    private void BTNWORKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNWORKSActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[4]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNWORKSActionPerformed

    private void BTNMETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMETActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[1]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNMETActionPerformed

    private void BTNFINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFINEActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[2]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNFINEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(artintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(artintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(artintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(artintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new artintern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAGO;
    private javax.swing.JButton BTNFINE;
    private javax.swing.JButton BTNGEORGIAN;
    private javax.swing.JButton BTNGOOGLE;
    private javax.swing.JButton BTNMET;
    private javax.swing.JButton BTNQUEENS;
    private javax.swing.JButton BTNRBC;
    private javax.swing.JButton BTNSICKKIDS;
    private javax.swing.JButton BTNUOFT;
    private javax.swing.JButton BTNWILDLIFE;
    private javax.swing.JButton BTNWORKS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
