
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300037574
 */
public class lawintern extends javax.swing.JFrame {

    /**
     * Creates new form lawintern
     */
    public lawintern() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 241, 142)); //set background colour
    }
    
    
    //array of string links
    String alllinks [] = {"https://councilofeducators.ca/search-programs/program.html?id=71#:~:text=During%20the%20Law%20YSP%2C%20students,a%20variety%20of%20stimulating%20environments.",
        "https://www.ourcommons.ca/About/Employment/youth-e.html", "https://slp2021ple.infolib.ca/summer-leadership-program-2021-program-overview/",
        "https://www.nortonrosefulbright.com/en-ca/careers/students/programs/quebec", 
    "https://www.law.utoronto.ca/student-life/career-development-office/summer-internship-programs"};
    
    //method to use hyperlink
    public static String hyperlink (String link){ 
        try {
            URI uri = new URI(link);
            Desktop desktop = null;
            if (Desktop.isDesktopSupported()) {
              desktop = Desktop.getDesktop();
            }

      if (desktop != null)
            desktop.browse(uri);
        } catch (IOException ioe) {
          ioe.printStackTrace(); 
        } catch (URISyntaxException use) {
          use.printStackTrace();
        } 
        return link; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNWILDLIFE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTNRBC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNUOFT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTNGOOGLE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNQUEENS = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BTNSICKKIDS = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTNWILDLIFE1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BTNRBC1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BTNUOFT1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BTNGOOGLE1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BTNSICKKIDS1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        BTNWILDLIFE.setText("Wildlife");
        BTNWILDLIFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNWILDLIFEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("STEM Internship Opportunities!");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("4. Wildlife Leadership");

        BTNRBC.setText("RBC");
        BTNRBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRBCActionPerformed(evt);
            }
        });

        jLabel9.setText("Get outside and connect with the environment while learning!");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("1. RBC Summer Tech Labs");

        BTNUOFT.setText("UofT");
        BTNUOFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUOFTActionPerformed(evt);
            }
        });

        jLabel2.setText("Design, develop, and test a prototype for a business unit at RBC!");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("5. UofT Academic Program");

        BTNGOOGLE.setText("Google");
        BTNGOOGLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGOOGLEActionPerformed(evt);
            }
        });

        jLabel11.setText("Challenges, engaging projects, and networking at University of Toronto!");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("2. Google Computer Science");

        BTNQUEENS.setText("Queen's");
        BTNQUEENS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNQUEENSActionPerformed(evt);
            }
        });

        jLabel5.setText("Innovate, program, and design at the Google office!");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("6. Queen's Computing");

        BTNSICKKIDS.setText("Sick Kids");
        BTNSICKKIDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSICKKIDSActionPerformed(evt);
            }
        });

        jLabel13.setText("Work in a computing research lab with computing professors!");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("3. StAr Sick Kids");

        jLabel7.setText("Interact with world-renowned researchers and medical professionals!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNWILDLIFE1.setText("NR");
        BTNWILDLIFE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNWILDLIFE1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        jLabel14.setText("LAW Internship Opportunities!");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setText("4. Norton Rose");

        BTNRBC1.setText("YSP");
        BTNRBC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRBC1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Become familiar with our culture and our wide human and legal resources.");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("1. LAW YSP");

        BTNUOFT1.setText("UofT");
        BTNUOFT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUOFT1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Discuss  advanced legal concepts, learning about the Canadian legal system");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setText("5. UofT LAW Program");

        BTNGOOGLE1.setText("HOC");
        BTNGOOGLE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGOOGLE1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Enable students to pursue summer opportunities in public law or international human rights!");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setText("2. House of Commons");

        jLabel22.setText("Provides fulfilling and rewarding employment opportunities to youth");

        BTNSICKKIDS1.setText("SLP");
        BTNSICKKIDS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSICKKIDS1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel25.setText("3. Summer Leadership Program");

        jLabel26.setText("Developed to invest in the future success of young people");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel26)
                            .addComponent(jLabel22)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel25)
                            .addComponent(jLabel16))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(198, 198, 198))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(100, 100, 100)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BTNSICKKIDS1)
                                            .addComponent(BTNWILDLIFE1))
                                        .addGap(147, 147, 147))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BTNGOOGLE1)
                                        .addGap(155, 155, 155)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BTNRBC1)
                                    .addGap(152, 152, 152)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNUOFT1)
                                .addGap(159, 159, 159))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(BTNRBC1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(BTNGOOGLE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(BTNSICKKIDS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(BTNWILDLIFE1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addComponent(BTNUOFT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNWILDLIFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNWILDLIFEActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[3]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNWILDLIFEActionPerformed

    private void BTNRBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRBCActionPerformed

        hyperlink(alllinks[0]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNRBCActionPerformed

    private void BTNUOFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUOFTActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[4]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNUOFTActionPerformed

    private void BTNGOOGLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGOOGLEActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[1]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNGOOGLEActionPerformed

    private void BTNQUEENSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNQUEENSActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[5]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNQUEENSActionPerformed

    private void BTNSICKKIDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSICKKIDSActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[2]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNSICKKIDSActionPerformed

    private void BTNWILDLIFE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNWILDLIFE1ActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[3]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNWILDLIFE1ActionPerformed

    private void BTNRBC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRBC1ActionPerformed

        hyperlink(alllinks[0]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNRBC1ActionPerformed

    private void BTNUOFT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUOFT1ActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[4]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNUOFT1ActionPerformed

    private void BTNGOOGLE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGOOGLE1ActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[1]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNGOOGLE1ActionPerformed

    private void BTNSICKKIDS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSICKKIDS1ActionPerformed
        // TODO add your handling code here:
        hyperlink(alllinks[2]); //when user clicks this button, direct them to this link of the array
    }//GEN-LAST:event_BTNSICKKIDS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lawintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lawintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lawintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lawintern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lawintern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGOOGLE;
    private javax.swing.JButton BTNGOOGLE1;
    private javax.swing.JButton BTNQUEENS;
    private javax.swing.JButton BTNRBC;
    private javax.swing.JButton BTNRBC1;
    private javax.swing.JButton BTNSICKKIDS;
    private javax.swing.JButton BTNSICKKIDS1;
    private javax.swing.JButton BTNUOFT;
    private javax.swing.JButton BTNUOFT1;
    private javax.swing.JButton BTNWILDLIFE;
    private javax.swing.JButton BTNWILDLIFE1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
