
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300037574
 */
public class oo extends javax.swing.JFrame {

    /**
     * Creates new form oo
     */
    public oo() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(147, 245, 202)); //set background colour
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNSTEMINTERN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNARTSINTERN = new javax.swing.JButton();
        BTNLAWINTERN = new javax.swing.JButton();
        BTNSTEMSCHOLAR = new javax.swing.JButton();
        BTNARTSSCHOLAR = new javax.swing.JButton();
        BTNLAWSCHOLAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTNQUIZ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNSTEMINTERN.setText("STEM");
        BTNSTEMINTERN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSTEMINTERNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Operation Opportunities!");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("This is a database meant for students seeking opportunities! Follow the instructions below to proceed!");

        jLabel3.setText("Click the button below to proceed to INTERNSHIP opportunities, in the selected field.");

        BTNARTSINTERN.setText("ARTS");
        BTNARTSINTERN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNARTSINTERNActionPerformed(evt);
            }
        });

        BTNLAWINTERN.setText("LAW");
        BTNLAWINTERN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLAWINTERNActionPerformed(evt);
            }
        });

        BTNSTEMSCHOLAR.setText("STEM");
        BTNSTEMSCHOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSTEMSCHOLARActionPerformed(evt);
            }
        });

        BTNARTSSCHOLAR.setText("ARTS");
        BTNARTSSCHOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNARTSSCHOLARActionPerformed(evt);
            }
        });

        BTNLAWSCHOLAR.setText("LAW");
        BTNLAWSCHOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLAWSCHOLARActionPerformed(evt);
            }
        });

        jLabel5.setText("Click the button below to proceed to SCHOLARSHIPS, in the selected field.");

        jLabel6.setText("Don't know what field you belong in? Take the CAREER QUIZ!!");

        BTNQUIZ.setText("CAREER QUIZ");
        BTNQUIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNQUIZActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stem.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/art.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/law.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gen.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(BTNSTEMINTERN)
                                .addGap(68, 68, 68)
                                .addComponent(BTNARTSINTERN)
                                .addGap(64, 64, 64)
                                .addComponent(BTNLAWINTERN))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel8)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel10))
                            .addComponent(jLabel6)
                            .addComponent(BTNQUIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(BTNSTEMSCHOLAR)
                                .addGap(60, 60, 60)
                                .addComponent(BTNARTSSCHOLAR)
                                .addGap(68, 68, 68)
                                .addComponent(BTNLAWSCHOLAR)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSTEMINTERN)
                    .addComponent(BTNARTSINTERN)
                    .addComponent(BTNLAWINTERN))
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSTEMSCHOLAR)
                    .addComponent(BTNARTSSCHOLAR)
                    .addComponent(BTNLAWSCHOLAR))
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNQUIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSTEMINTERNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSTEMINTERNActionPerformed
        intern f2 = new intern(); //make frame visible
        f2.setVisible(true);
        
    }//GEN-LAST:event_BTNSTEMINTERNActionPerformed

    private void BTNARTSINTERNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNARTSINTERNActionPerformed
        artintern f3 = new artintern(); //make frame visible
        f3.setVisible(true);
    }//GEN-LAST:event_BTNARTSINTERNActionPerformed

    private void BTNQUIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNQUIZActionPerformed
        quiz f6 = new quiz(); //make frame visible
        f6.setVisible(true);
    }//GEN-LAST:event_BTNQUIZActionPerformed

    private void BTNLAWINTERNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLAWINTERNActionPerformed
        lawintern f5 = new lawintern(); //make frame visible
        f5.setVisible(true);
    }//GEN-LAST:event_BTNLAWINTERNActionPerformed

    private void BTNSTEMSCHOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSTEMSCHOLARActionPerformed
        stemscholar f6 = new stemscholar(); //make frame visible
        f6.setVisible(true);
    }//GEN-LAST:event_BTNSTEMSCHOLARActionPerformed

    private void BTNARTSSCHOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNARTSSCHOLARActionPerformed
        artscholar f7 = new artscholar(); //make frame visible
        f7.setVisible(true);
    }//GEN-LAST:event_BTNARTSSCHOLARActionPerformed

    private void BTNLAWSCHOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLAWSCHOLARActionPerformed
        lawscholar f8 = new lawscholar(); //make frame visible
        f8.setVisible(true);
    }//GEN-LAST:event_BTNLAWSCHOLARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNARTSINTERN;
    private javax.swing.JButton BTNARTSSCHOLAR;
    private javax.swing.JButton BTNLAWINTERN;
    private javax.swing.JButton BTNLAWSCHOLAR;
    private javax.swing.JButton BTNQUIZ;
    private javax.swing.JButton BTNSTEMINTERN;
    private javax.swing.JButton BTNSTEMSCHOLAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
