
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300037574
 */
public class quiz extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    public quiz() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(238, 128, 168)); //set background colour
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblquestion1 = new javax.swing.JLabel();
        btntakequiz = new javax.swing.JButton();
        txtans1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblquestion2 = new javax.swing.JLabel();
        lblquestion3 = new javax.swing.JLabel();
        lblquestion4 = new javax.swing.JLabel();
        txtans2 = new javax.swing.JTextField();
        txtans3 = new javax.swing.JTextField();
        txtans4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnresult = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblrec = new javax.swing.JLabel();
        lblrecsec = new javax.swing.JLabel();
        lblrecthird = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblquestion1.setText("Question 1");

        btntakequiz.setText("Take quiz");
        btntakequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntakequizActionPerformed(evt);
            }
        });

        txtans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtans1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Welcome to the CAREER QUIZ!!!");

        lblquestion2.setText("Question2");

        lblquestion3.setText("Question 3");

        lblquestion4.setText("Question 4");

        txtans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtans2ActionPerformed(evt);
            }
        });

        txtans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtans3ActionPerformed(evt);
            }
        });

        txtans4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtans4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Type. Below are options.");

        jLabel3.setText("\"9\", \"10\", \"11\", \"12\"");

        jLabel4.setText("\"GTA\", \"Other\"");

        jLabel5.setText("\"Science\", \"Writing\"");

        jLabel6.setText("\"Tech\", \"Creativity\"");

        btnresult.setText("Get My Results!");
        btnresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresultActionPerformed(evt);
            }
        });

        lblrec.setText("...");

        lblrecsec.setText("...");

        lblrecthird.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnresult)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblquestion4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtans4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblquestion3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtans3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblquestion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtans2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblquestion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtans1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntakequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrec)
                            .addComponent(lblrecsec)
                            .addComponent(jLabel7)
                            .addComponent(lblrecthird))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(btntakequiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquestion1)
                    .addComponent(txtans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquestion2)
                    .addComponent(txtans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquestion3)
                    .addComponent(txtans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquestion4)
                    .addComponent(txtans4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(btnresult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblrec)
                .addGap(11, 11, 11)
                .addComponent(lblrecsec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblrecthird)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntakequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntakequizActionPerformed
       
        
       //string array
       String question [ ] = new String [5];
       
       //read text file and store in array
       //text file has the questions of the quiz
        try{
         FileReader file = new FileReader("quiz.txt");
         
         BufferedReader buffer = new BufferedReader(file);
         
         for (int i = 0; i < 4; i++){ 
            question[i]=buffer.readLine();
         }
         buffer.close();
        } 
        //if reading file does not work, output that
        catch (IOException e){
            System.out.println("Sorry, file was not found.");
               }
        
        //set the labels to the questions
        lblquestion1.setText(question[0]); 
        lblquestion2.setText(question[1]);
        lblquestion3.setText(question[2]);
        lblquestion4.setText(question[3]);
        
        
        
        
    }//GEN-LAST:event_btntakequizActionPerformed

    private void txtans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtans1ActionPerformed

    private void txtans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtans2ActionPerformed

    private void txtans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtans3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtans3ActionPerformed

    private void txtans4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtans4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtans4ActionPerformed

    private void btnresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresultActionPerformed
        // TODO add your handling code here:
        
        //get user input
        String ans1 = (txtans1.getText());
        String ans2 = (txtans2.getText());
        String ans3 = (txtans3.getText());
        String ans4 = (txtans4.getText());
        
        //check each scenario for grade and interest and output personalized reccomendation
        //Science
        if (ans2.equals("9") && ans4.equals("Science")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field. ");
            lblrecthird.setText("Try the StAr Sick Kids!");
            }
        
        if (ans2.equals("10") && ans4.equals("Science")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the Wildlife Leadership");
            }
        
        if (ans2.equals("11") && ans4.equals("Science")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the UofT Academic Program");
            }
        
        if (ans2.equals("12") && ans4.equals("Science")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the UofT Academic Program");
            }
        
        //Writing
        
        if (ans2.equals("9") && ans4.equals("Writing")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Law field.");
            lblrecthird.setText("Try the Law YSP program.");
            }
        
        if (ans2.equals("10") && ans4.equals("Writing")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Law field.");
            lblrecthird.setText("Try the House of Commons program.");
            }
        
        if (ans2.equals("11") && ans4.equals("Writing")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Law field.");
            lblrecthird.setText("Try the Law SLP.");
            }
        
        if (ans2.equals("12") && ans4.equals("Writing")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Law field.");
            lblrecthird.setText("Try the UofT Law program.");
            }
        
        //Tech
        if (ans2.equals("9") && ans4.equals("Tech")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the RBC Summer Tech Labs.");
            }
        
        if (ans2.equals("10") && ans4.equals("Tech")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the RBC Summer Tech Labs.");
            }
        
        if (ans2.equals("11") && ans4.equals("Tech")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the Google CS program.");
            }
        
        if (ans2.equals("12") && ans4.equals("Tech")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the STEM field.");
            lblrecthird.setText("Try the Queen's Computing Program.");
            }
        //Creativity
        if (ans2.equals("9") && ans4.equals("Creativity")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Arts field.");
            lblrecthird.setText("Try the RBC Summer Tech Labs.");
            }
        
        if (ans2.equals("10") && ans4.equals("Creativity")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Arts field.");
            lblrecthird.setText("Try the Experience Georgian program.");
            }
        
        if (ans2.equals("11") && ans4.equals("Creativity")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Arts field.");
            lblrecthird.setText("Try the Met program.");
            }
        
        if (ans2.equals("12") && ans4.equals("Creativity")){
            lblrec.setText("Hi, " + ans1);
            lblrecsec.setText("You should try the Arts field.");
            lblrecthird.setText("Try the Works program.");
            }
        
    }//GEN-LAST:event_btnresultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnresult;
    private javax.swing.JButton btntakequiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblquestion1;
    private javax.swing.JLabel lblquestion2;
    private javax.swing.JLabel lblquestion3;
    private javax.swing.JLabel lblquestion4;
    private javax.swing.JLabel lblrec;
    private javax.swing.JLabel lblrecsec;
    private javax.swing.JLabel lblrecthird;
    private javax.swing.JTextField txtans1;
    private javax.swing.JTextField txtans2;
    private javax.swing.JTextField txtans3;
    private javax.swing.JTextField txtans4;
    // End of variables declaration//GEN-END:variables
}
